services:

  tic-tac-toe-game:
    image: mykniz/tic-tac-toe-game:latest
    container_name: tic-tac-toe-game
#    build:
#      dockerfile: Dockerfile
#      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    networks:
      - game_net
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - game_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  game_net:
    driver: bridge

volumes:
  postgres:

